import React from "react";
import {
    Document,
    Page,
    Text,
    View,
    StyleSheet,
    Font,
} from "@react-pdf/renderer";

interface Report {
    id: string;
    title: string;
    date: string;
    status: string;
    downloadLink?: string | null;
}

interface ReportPDFProps {
    reports: Report[];
    studentName: string;
}

// Styles for the PDF
const styles = StyleSheet.create({
    page: {
        padding: 30,
        fontSize: 12,
        fontFamily: "Helvetica",
    },
    header: {
        fontSize: 18,
        marginBottom: 20,
        textAlign: "center",
        color: "#4F46E5", // Indigo-600
    },
    table: {
        display: "table",
        width: "auto",
        borderStyle: "solid",
        borderWidth: 1,
        borderColor: "#ddd",
        marginBottom: 20,
    },
    tableRow: {
        flexDirection: "row",
    },
    tableHeaderCell: {
        margin: 4,
        fontWeight: "bold",
        borderStyle: "solid",
        borderBottomWidth: 1,
        borderColor: "#4F46E5",
        padding: 6,
        flex: 1,
    },
    tableCell: {
        margin: 4,
        padding: 6,
        flex: 1,
        borderStyle: "solid",
        borderBottomWidth: 1,
        borderColor: "#ddd",
    },
    footer: {
        fontSize: 10,
        color: "#999",
        textAlign: "center",
        marginTop: 40,
    },
});

const ReportPDF: React.FC<ReportPDFProps> = ({ reports, studentName }) => (
    <Document>
        <Page size="A4" style={styles.page}>
            <Text style={styles.header}>University Reports for {studentName}</Text>

            <View style={styles.table}>
                <View style={styles.tableRow}>
                    <Text style={styles.tableHeaderCell}>Title</Text>
                    <Text style={styles.tableHeaderCell}>Date</Text>
                    <Text style={styles.tableHeaderCell}>Status</Text>
                </View>
                {reports.map((report) => (
                    <View style={styles.tableRow} key={report.id}>
                        <Text style={styles.tableCell}>{report.title}</Text>
                        <Text style={styles.tableCell}>{new Date(report.date).toLocaleDateString()}</Text>
                        <Text style={styles.tableCell}>{report.status}</Text>
                    </View>
                ))}
            </View>

            <Text style={styles.footer}>Generated by University System © {new Date().getFullYear()}</Text>
        </Page>
    </Document>
);

export default ReportPDF;
