import React from "react";
import {
    Document,
    Page,
    Text,
    View,
    StyleSheet,
    Font,
} from "@react-pdf/renderer";

// Optional: Register custom fonts if you want

const styles = StyleSheet.create({
    page: {
        padding: 30,
        fontSize: 12,
        fontFamily: "Helvetica",
    },
    header: {
        fontSize: 18,
        marginBottom: 10,
        fontWeight: "bold",
        textAlign: "center",
        color: "#2c3e50",
    },
    section: {
        marginBottom: 12,
    },
    label: {
        fontWeight: "bold",
        marginBottom: 4,
        color: "#34495e",
    },
    text: {
        marginBottom: 8,
    },
    footer: {
        fontSize: 10,
        color: "#7f8c8d",
        textAlign: "center",
        marginTop: 20,
    },
});

interface ReportDocumentProps {
    report: {
        id: string;
        title: string;
        date: string;
        status: string;
        downloadLink?: string | null;
    };
}

export default function ReportDocument({ report }: ReportDocumentProps) {
    return (
        <Document>
            <Page style={styles.page}>
                <Text style={styles.header}>University Report</Text>

                <View style={styles.section}>
                    <Text style={styles.label}>Title:</Text>
                    <Text style={styles.text}>{report.title}</Text>
                </View>

                <View style={styles.section}>
                    <Text style={styles.label}>Date:</Text>
                    <Text style={styles.text}>{new Date(report.date).toLocaleDateString()}</Text>
                </View>

                <View style={styles.section}>
                    <Text style={styles.label}>Status:</Text>
                    <Text style={styles.text}>{report.status}</Text>
                </View>

                {report.downloadLink && (
                    <View style={styles.section}>
                        <Text style={styles.label}>Download Link:</Text>
                        <Text style={styles.text}>{report.downloadLink}</Text>
                    </View>
                )}

                <Text style={styles.footer}>Generated by University Portal</Text>
            </Page>
        </Document>
    );
}