"use client";

import { useParams } from "next/navigation";
import { ArrowLeft, Info } from "lucide-react";
import Link from "next/link";

export default function ReportDetailsPage() {
    const params = useParams();
    const reportId = params?.id || "Unknown";

    return (
        <div className="p-6 bg-gray-50 min-h-screen space-y-6">
            {/* Header */}
            <div className="flex items-center gap-3">
                <Link
                    href="/dashboard/admin/reports"
                    className="text-gray-600 hover:text-gray-900 flex items-center gap-1"
                >
                    <ArrowLeft size={18} /> Back
                </Link>
            </div>

            {/* Title */}
            <div className="flex items-center gap-3">
                <Info size={32} className="text-green-600" />
                <h1 className="text-2xl font-bold">Report Details — {reportId}</h1>
            </div>

            {/* Details */}
            <div className="bg-white rounded-lg shadow p-6 space-y-4">
                <div>
                    <p className="font-medium text-gray-700">Report Name:</p>
                    <p className="text-gray-600">Example Report Title</p>
                </div>
                <div>
                    <p className="font-medium text-gray-700">Created On:</p>
                    <p className="text-gray-600">2025-06-12</p>
                </div>
                <div>
                    <p className="font-medium text-gray-700">Status:</p>
                    <span className="px-2 py-1 bg-green-100 text-green-700 rounded-full text-sm">
                        Completed
                    </span>
                </div>
                <div>
                    <p className="font-medium text-gray-700">Generated By:</p>
                    <p className="text-gray-600">Admin User</p>
                </div>
                <div>
                    <p className="font-medium text-gray-700">Description:</p>
                    <p className="text-gray-600">
                        This report contains a summary of key metrics and insights for the
                        selected period.
                    </p>
                </div>
            </div>
        </div>
    );
}
